# 추천시스템

## 콘텐츠 기반 추천

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data_resources/tmdb_5000_movies.csv")

df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [7]:
movies = df[["id", "title", "genres", "vote_average", 'vote_count', 'popularity', 'keywords', 'overview']]
movies.head()

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 878, ""name"": ""Science Fiction""}]",7.2,11800,150.437577,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""space war""}, {""id"": 3388, ""name"": ""space colony""}, {""id"": 3679, ""name"": ""society""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 9685, ""name"": ""futuristic""}, {""id"": 9840, ""name"": ""romance""}, {""id"": 9882, ""name"": ""space""}, {""id"": 9951, ""name"": ""alien""}, {""id"": 10148, ""name"": ""tribe""}, {""id"": 10158, ""na...","In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]",6.9,4500,139.082615,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""name"": ""drug abuse""}, {""id"": 911, ""name"": ""exotic island""}, {""id"": 1319, ""name"": ""east india trading company""}, {""id"": 2038, ""name"": ""love of one's life""}, {""id"": 2052, ""name"": ""traitor""}, {""id"": 2580, ""name"": ""shipwreck""}, {""id"": 2660, ""name"": ""strong woman""}, {""id"": 3799, ""name"": ""ship""}, {""id"": 5740, ""name"": ""alliance""}, {""id"": 5941, ""name"": ""caly...","Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 80, ""name"": ""Crime""}]",6.3,4466,107.376788,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 4289, ""name"": ""secret agent""}, {""id"": 9663, ""name"": ""sequel""}, {""id"": 14555, ""name"": ""mi6""}, {""id"": 156095, ""name"": ""british secret service""}, {""id"": 158431, ""name"": ""united kingdom""}]","A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name"": ""Thriller""}]",7.6,9106,112.312950,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853, ""name"": ""crime fighter""}, {""id"": 949, ""name"": ""terrorist""}, {""id"": 1308, ""name"": ""secret identity""}, {""id"": 1437, ""name"": ""burglar""}, {""id"": 3051, ""name"": ""hostage drama""}, {""id"": 3562, ""name"": ""time bomb""}, {""id"": 6969, ""name"": ""gotham city""}, {""id"": 7002, ""name"": ""vigilante""}, {""id"": 9665, ""name"": ""cover-up""}, {""id"": 9715, ""name"": ""superhero""}, ...","Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a cit..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 878, ""name"": ""Science Fiction""}]",6.1,2124,43.926995,"[{""id"": 818, ""name"": ""based on novel""}, {""id"": 839, ""name"": ""mars""}, {""id"": 1456, ""name"": ""medallion""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 7376, ""name"": ""princess""}, {""id"": 9951, ""name"": ""alien""}, {""id"": 10028, ""name"": ""steampunk""}, {""id"": 10539, ""name"": ""martian""}, {""id"": 10685, ""name"": ""escape""}, {""id"": 161511, ""name"": ""edgar rice burroughs""}, {""id"": 163252, ""name"": ""alien race""}, ...","John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands."

In [6]:
pd.set_option('max_colwidth', 400)

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   int64
 1   title         4803 non-null   object
 2   genres        4803 non-null   object
 3   vote_average  4803 non-null   float64
 4   vote_count    4803 non-null   int64
 5   popularity    4803 non-null   float64
 6   keywords      4803 non-null   object
 7   overview      4800 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 300.3+ KB

## 리스트 형태의 문자열데이터를 전처리

In [12]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
from ast import literal_eval

result = literal_eval(movies['genres'][0])

result

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
movies['genres'] = movies["genres"].apply(literal_eval)

In [18]:

movies['genres'][0]

movies['genres']

0       [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]
1                                               [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}]
2                                                 [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 80, 'name': 'Crime'}]
3                     [{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
4                                      [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 878, 'name': 'Science Fiction'}]
                                                                         ...
4798                                               [{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 53, 'name': 'Thriller'}]
4799                                                                          [{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
4800          [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}, {'id': 10770, 'name': 'TV Movie'}]
4801                                                                                                                                        []
4802                                                                                                       [{'id': 99, 'name': 'Documentary'}]
Name: genres, Length: 4803, dtype: object

In [21]:
movies["keywords"] = movies["keywords"].apply(literal_eval)

C:\Users\user\AppData\Local\Temp\ipykernel_37328\784109267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["keywords"] = movies["keywords"].apply(literal_eval)

In [23]:
movies.keywords[0]

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

## 칼럼을 벡터화

In [26]:
name_result = []

for genres in movies["genres"] :
    temp_list = []
    for genre in genres:
        temp_list.append(genre["name"])
    name_result.append(temp_list)

name_result

[['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Crime'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Fantasy', 'Action', 'Adventure'],
 ['Animation', 'Family'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy', 'Action', 'Science Fiction'],
 ['Adventure', 'Action', 'Thriller', 'Crime'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Western'],
 ['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Adventure', 'Action', 'Fantasy'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Drama', 'Action'],
 ['Drama', 'Romance', 'Thriller'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Thriller', 'Action', 'Adventure', 'Science Fiction'],
 ['Action', 'Adventure', 'Science Fiction', 'Thriller'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Family', 'Fantasy', 'Adventure'],
 ['Adventure', 'Action', 'Science Fiction', 'Thriller'],
 ['Animation', 'Family'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Fantasy', 'Adventure', 'Family'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Animation', 'Family', 'Adventure', 'Comedy'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Animation', 'Family', 'Comedy'],
 ['Action', 'Science Fiction', 'Thriller'],
 ['Action'],
 ['Action', 'Drama', 'Horror', 'Science Fiction', 'Thriller'],
 ['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Action', 'Family', 'Fantasy'],
 ['Drama', 'Romance'],
 ['Adventure', 'Fantasy', 'Action', 'Romance'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Adventure', 'Action'],
 ['Adventure', 'Animation', 'Family'],
 ['Animation', 'Adventure', 'Comedy', 'Family', 'Action', 'Fantasy'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Animation', 'Family'],
 ['Action', 'Comedy', 'Crime', 'Thriller'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Animation', 'Drama'],
 ['Science Fiction', 'Fantasy', 'Action', 'Adventure'],
 ['Action', 'Adventure'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Science Fiction'],
 ['Drama', 'Action', 'Crime', 'Thriller'],
 ['Animation', 'Comedy', 'Family', 'Adventure'],
 ['Animation', 'Family', 'Adventure', 'Science Fiction'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Adventure', 'Drama', 'Family'],
 ['Action', 'Adventure', 'Comedy', 'Science Fiction', 'Western'],
 ['Adventure', 'Action', 'Fantasy'],
 ['Action', 'Adventure', 'Crime', 'Fantasy', 'Science Fiction'],
 ['Fantasy', 'Comedy', 'Family'],
 ['Action', 'Science Fiction'],
 ['Adventure', 'Action'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Drama', 'Comedy', 'Animation', 'Family'],
 ['Family', 'Adventure', 'Drama', 'Fantasy'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Drama'],
 ['Fantasy', 'Adventure', 'Action', 'Family', 'Romance'],
 ['Science Fiction', 'Action', 'Drama', 'Thriller'],
 ['Action', 'Adventure', 'Science Fiction', 'Romance'],
 ['Drama', 'Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Comedy', 'Adventure', 'Fantasy', 'Animation', 'Family'],
 ['Adventure', 'Family', 'Mystery', 'Science Fiction'],
 ['Adventure', 'Family', 'Animation', 'Action', 'Comedy'],
 ['Family', 'Animation', 'Comedy', 'Adventure'],
 ['Adventure', 'Animation', 'Family', 'Fantasy'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Fantasy', 'Adventure', 'Animation', 'Family'],
 ['Action', 'Thriller', 'Science Fiction'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Adventure', 'Drama', 'Science Fiction'],
 ['Action', 'Thriller', 'Science Fiction', 'Mystery', 'Adventure'],
 ['Action', 'Adventure', 'Drama', 'Horror', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Crime', 'Thriller'],
 ['Fantasy', 'Drama', 'Thriller', 'Mystery', 'Romance'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Fantasy', 'Adventure', 'Action', 'Comedy', 'Drama'],
 ['Adventure', 'Action', 'Drama', 'Thriller'],
 ['Fantasy'],
 ['Fantasy', 'Adventure', 'Animation', 'Comedy', 'Family'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Science Fiction', 'Action', 'Thriller', 'Adventure'],
 ['Adventure', 'Family', 'Fantasy'],
 ['History', 'Romance', 'War'],
 ['Adventure', 'Science Fiction', 'Action'],
 ['War', 'History', 'Action', 'Adventure', 'Drama', 'Romance'],
 ['Adventure', 'Fantasy', 'Family', 'Mystery'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Fantasy', 'Action'],
 ['Drama', 'Horror', 'Action', 'Thriller', 'Science Fiction'],
 ['Adventure', 'Comedy', 'Family', 'Fantasy'],
 ['Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Action', 'Crime', 'Drama'],
 ['Family', 'Animation'],
 ['Adventure', 'Fantasy', 'Action', 'Comedy', 'Family'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Animation', 'Adventure', 'Family'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Science Fiction', 'Thriller'],
 ['Thriller', 'Mystery'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Animation', 'Family', 'Adventure', 'Comedy'],
 ['Fantasy', 'Action', 'Adventure', 'Family', 'Comedy'],
 ['Adventure'],
 ['Comedy', 'Fantasy'],
 ['Action', 'Adventure', 'Thriller'],
 ['Drama', 'Horror', 'Thriller'],
 ['Family', 'Animation', 'Adventure', 'Comedy'],
 ['Animation', 'Family'],
 ['Action', 'Adventure', 'Family', 'Fantasy'],
 ['Adventure', 'Action', 'Thriller'],
 ['Action', 'Drama', 'Thriller'],
 ['Adventure', 'Animation', 'Family'],
 ['Adventure', 'Animation', 'Comedy', 'Family'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Animation', 'Adventure', 'Family'],
 ['Adventure', 'Drama', 'War'],
 ['Animation', 'Family'],
 ['Adventure', 'Action', 'Thriller'],
 ['Action', 'Fantasy', 'Comedy'],
 ['Action', 'Thriller', 'Science Fiction', 'Adventure'],
 ['Action', 'Adventure', 'Comedy', 'Science Fiction'],
 ['Adventure', 'Action', 'Animation'],
 ['Action', 'Adventure', 'Animation', 'Comedy', 'Family'],
 ['Action', 'Thriller', 'Adventure'],
 ['Fantasy', 'Animation', 'Family'],
 ['Comedy'],
 ['Drama', 'Action', 'War', 'History'],
 ['Adventure', 'Drama', 'Action'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Fantasy', 'Action'],
 ['Fantasy', 'Action', 'Adventure', 'Animation', 'Comedy', 'Family'],
 ['Fantasy'],
 ['Action'],
 ['Action', 'Mystery', 'Science Fiction'],
 ['Action', 'Adventure', 'Comedy', 'Crime', 'Thriller'],
 ['Drama', 'Action', 'Science Fiction'],
 ['Adventure', 'Action', 'Science Fiction', 'Thriller'],
 ['Action', 'Adventure', 'Comedy', 'Drama', 'Mystery'],
 ['Adventure',
  'Action',
  'Animation',
  'Fantasy',
  'Science Fiction',
  'Thriller'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Adventure', 'Action', 'Thriller'],
 ['Adventure'],
 ['Adventure', 'Fantasy', 'Drama', 'Romance'],
 ['Animation', 'Comedy', 'Family'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Western', 'Drama', 'Adventure', 'Thriller'],
 ['Animation', 'Family'],
 ['Animation', 'Comedy', 'Family', 'Western', 'Adventure'],
 ['Family', 'Animation', 'Adventure', 'Comedy'],
 ['Action', 'Drama', 'Mystery', 'Thriller'],
 ['Adventure', 'Animation', 'Family', 'Comedy'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Fantasy', 'Comedy', 'Animation', 'Science Fiction', 'Family'],
 ['Adventure', 'Thriller', 'Science Fiction'],
 ['Adventure', 'Action', 'Comedy', 'Thriller', 'Crime'],
 ['Action', 'Adventure', 'Animation', 'Family', 'Fantasy'],
 ['Action', 'Mystery', 'Thriller'],
 ['Drama', 'Adventure'],
 ['Adventure', 'Animation', 'Mystery'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Drama'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Animation', 'Family'],
 ['Adventure', 'Comedy', 'Fantasy', 'Family'],
 ['Animation', 'Action', 'Comedy', 'Family', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Fantasy', 'Action', 'Comedy', 'Crime'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Science Fiction', 'Adventure', 'Thriller'],
 ['Thriller', 'Mystery'],
 ['Animation', 'Adventure', 'Comedy', 'Family'],
 ['Adventure', 'Action', 'Science Fiction', 'Thriller'],
 ['Action', 'Thriller', 'Crime'],
 ['Adventure', 'Action', 'Crime', 'Mystery'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Thriller'],
 ['Action', 'Crime', 'Fantasy'],
 ['Family', 'Comedy', 'Fantasy'],
 ['Action', 'Adventure', 'Science Fiction', 'Thriller'],
 ['Adventure', 'Action', 'Thriller'],
 ['Drama'],
 ['Adventure', 'Fantasy', 'Action', 'Thriller'],
 ['Adventure', 'Drama', 'Action'],
 ['Thriller', 'Action', 'Fantasy', 'Horror'],
 ['Action', 'Thriller'],
 ['Action', 'Adventure', 'Comedy'],
 ['Science Fiction', 'Adventure', 'Mystery'],
 ['Family', 'Adventure', 'Animation', 'Comedy'],
 ['Science Fiction', 'Action', 'Drama', 'Thriller'],
 ['Action', 'Science Fiction'],
 ['Action', 'Science Fiction'],
 ['Action', 'Family', 'Science Fiction'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Comedy'],
 ['Action', 'Science Fiction', 'Adventure', 'Mystery'],
 ['Science Fiction', 'Adventure', 'Action'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Animation', 'Comedy', 'Family'],
 ['Action', 'Science Fiction', 'Adventure', 'Fantasy'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Fantasy', 'Adventure', 'Comedy', 'Family'],
 ['Drama', 'Action', 'History', 'War'],
 ['Action', 'Adventure', 'Drama'],
 ['Science Fiction', 'Action', 'Adventure', 'Fantasy', 'Comedy'],
 ['Science Fiction', 'Thriller', 'Drama'],
 ['Action', 'Adventure', 'Thriller'],
 ['Fantasy', 'Action', 'Adventure', 'Comedy'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Action', 'Adventure', 'Comedy', 'Family', 'Fantasy'],
 ['Action', 'Drama', 'Thriller'],
 ['Adventure', 'Action', 'Thriller'],
 ['Drama', 'History', 'War', 'Action'],
 ['Thriller', 'Crime'],
 ['Action', 'Comedy', 'Drama', 'Thriller'],
 ['Adventure', 'Science Fiction', 'Thriller'],
 ['Drama'],
 ['Comedy'],
 ['Action', 'Crime', 'Comedy'],
 ['Action', 'War'],
 ['Animation', 'Family', 'Adventure', 'Comedy', 'Fantasy'],
 ['Animation', 'Family'],
 ['Adventure', 'Science Fiction'],
 ['Action', 'Science Fiction', 'Drama'],
 ['Fantasy', 'Family', 'Comedy', 'Animation'],
 ['Action', 'Adventure', 'Thriller'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Action', 'Thriller'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Comedy'],
 ['Drama'],
 ['Comedy', 'Fantasy', 'Family'],
 ['Action', 'Science Fiction'],
 ['Drama', 'Action', 'Adventure', 'History', 'War'],
 ['Animation', 'Fantasy', 'Family', 'Comedy'],
 ['Romance', 'Family', 'Animation', 'Music'],
 ['Drama', 'Adventure', 'Science Fiction'],
 ['Action', 'Thriller', 'Science Fiction', 'Adventure'],
 ['Comedy', 'Romance'],
 ['Action', 'Crime', 'Thriller'],
 ['Action', 'Drama', 'Adventure'],
 ['Action', 'Thriller', 'Science Fiction', 'Mystery'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Adventure', 'Action', 'Thriller'],
 ['Thriller', 'Science Fiction', 'Action', 'Adventure'],
 ['Action', 'Thriller', 'Science Fiction'],
 ['History', 'Crime', 'Drama'],
 ['Drama', 'Crime'],
 ['Action', 'Thriller'],
 ['Thriller', 'Drama', 'Crime'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Western'],
 ['Drama', 'Animation', 'Family'],
 ['Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Action', 'Adventure', 'Thriller'],
 ['Adventure', 'Action', 'Thriller', 'Mystery'],
 ['Fantasy', 'Action', 'Adventure', 'Family'],
 ['Family', 'Fantasy'],
 ['Animation', 'Adventure', 'Family', 'Fantasy'],
 ['Action', 'Thriller', 'Romance'],
 ['Action', 'Fantasy', 'Horror', 'Mystery'],
 ['Drama', 'Thriller', 'Action'],
 ['Crime', 'Drama', 'Comedy'],
 ['Action', 'Crime', 'Fantasy'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Drama', 'Science Fiction'],
 ['Animation', 'Adventure', 'Family', 'Fantasy'],
 ['Action', 'Crime'],
 ['Action', 'Adventure'],
 ['Adventure', 'Animation', 'Family', 'Fantasy', 'Science Fiction'],
 ['Adventure', 'Comedy', 'Science Fiction'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Crime', 'Thriller'],
 ['Fantasy', 'Comedy', 'Family', 'Adventure'],
 ['Thriller', 'Drama', 'Adventure', 'Action', 'History'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['War', 'Action', 'Adventure', 'Drama', 'Thriller'],
 ['Animation'],
 ['Crime', 'Drama', 'Mystery', 'Thriller'],
 ['Adventure', 'Action', 'Fantasy'],
 ['Drama', 'History', 'Crime'],
 ['Drama', 'History', 'War'],
 ['Animation', 'Comedy', 'Family'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Action', 'History', 'War'],
 ['Comedy'],
 ['Adventure', 'Fantasy', 'Action', 'Thriller', 'Science Fiction'],
 ['Comedy', 'Drama', 'Romance'],
 ['Adventure', 'Animation', 'Comedy', 'Family'],
 ['Animation', 'Comedy', 'Adventure', 'Family'],
 ['Romance', 'Fantasy', 'Family', 'Drama'],
 ['Fantasy', 'Drama'],
 ['Animation', 'Family'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy', 'Action', 'Thriller'],
 ['Thriller', 'Science Fiction', 'Drama', 'Mystery'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Thriller', 'Action', 'Drama', 'Science Fiction'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Action', 'Thriller'],
 ['Western', 'History', 'War'],
 ['Action', 'Adventure', 'Animation', 'Family'],
 ['Action', 'Adventure'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Action', 'Adventure', 'Comedy', 'Science Fiction'],
 ['Animation', 'Comedy', 'Family'],
 ['Action', 'Thriller'],
 ['Action', 'Comedy', 'Crime', 'Thriller'],
 ['Drama', 'Horror', 'Mystery', 'Thriller'],
 ['Animation', 'Comedy', 'Family'],
 ['Animation', 'Comedy', 'Family', 'Adventure'],
 ['Adventure', 'Comedy', 'Drama', 'Fantasy'],
 ['Action', 'Adventure', 'Comedy', 'Crime', 'Thriller'],
 ['Drama', 'Thriller', 'Crime'],
 ['Animation', 'Family', 'Adventure'],
 ['Action', 'Comedy'],
 ['Thriller', 'Crime', 'Mystery', 'Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Adventure', 'Crime', 'Mystery'],
 ['Drama'],
 ['Animation', 'Family', 'Adventure', 'Science Fiction'],
 ['Adventure', 'Animation', 'Comedy', 'Family'],
 ['Drama', 'Thriller', 'History', 'War'],
 ['Comedy', 'Action'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Drama', 'Science Fiction', 'Adventure'],
 ['Thriller', 'Fantasy', 'Comedy', 'Family', 'Mystery'],
 ['Drama', 'Science Fiction', 'Mystery'],
 ['Action', 'Science Fiction', 'Thriller'],
 ['Crime', 'Thriller'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Action', 'Adventure', 'Fantasy', 'Thriller'],
 ['Action', 'Adventure', 'Comedy', 'Crime', 'Mystery', 'Thriller'],
 ['Thriller', 'Action', 'Romance', 'Science Fiction', 'Adventure'],
 ['Action', 'Crime', 'Thriller'],
 ['Science Fiction'],
 ['Animation', 'Adventure', 'Comedy', 'Family'],
 ['Comedy', 'Science Fiction'],
 ['Science Fiction', 'Action', 'Drama', 'Thriller'],
 ['Crime', 'Thriller', 'Drama'],
 ['Drama', 'History', 'Thriller'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Romance', 'Drama', 'History'],
 ['Fantasy', 'Action', 'Family'],
 ['Drama', 'History'],
 ['Action', 'Adventure', 'Drama'],
 ['Adventure', 'Drama'],
 ['Animation', 'Comedy'],
 ['Action', 'Drama', 'Thriller'],
 ['Action', 'Thriller'],
 ['Thriller', 'Crime'],
 ['Adventure', 'Action', 'Thriller'],
 ['Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Comedy', 'Family', 'Fantasy', 'Romance'],
 ['Action', 'Thriller'],
 ['Comedy', 'Family'],
 ['Action', 'Comedy'],
 ['Comedy', 'Romance'],
 ['Action', 'Drama', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Crime', 'Thriller'],
 ['Adventure', 'Animation', 'Family'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['War'],
 ['Adventure', 'Action', 'Comedy', 'Thriller'],
 ['Adventure', 'Fantasy', 'Action', 'Comedy', 'Family'],
 ['Drama', 'History', 'Romance'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Drama', 'Animation', 'Family', 'Comedy'],
 ['Fantasy', 'Drama', 'Mystery'],
 ['Action', 'Thriller', 'Drama'],
 ['Drama', 'Music'],
 ['Adventure', 'Fantasy', 'Drama', 'Comedy', 'Science Fiction', 'Family'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Thriller', 'Adventure', 'Science Fiction'],
 ['Fantasy', 'Comedy', 'Romance', 'Science Fiction'],
 ['Mystery', 'Adventure', 'Comedy'],
 ['Action', 'Science Fiction'],
 ['Comedy', 'Drama', 'Fantasy', 'Romance'],
 ['Horror', 'Comedy', 'Fantasy'],
 ['Comedy', 'Family'],
 ['Adventure', 'Fantasy', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Science Fiction'],
 ['Crime', 'Drama', 'Mystery', 'Thriller'],
 ['Science Fiction'],
 ['Fantasy', 'Comedy'],
 ['Thriller', 'Adventure', 'Action'],
 ['Adventure', 'Action', 'Thriller'],
 ['Science Fiction', 'Adventure', 'Fantasy'],
 ['Comedy'],
 ['Action', 'Fantasy'],
 ['Comedy', 'Animation', 'Family'],
 ['Animation', 'Family'],
 ['Comedy', 'Family', 'Fantasy'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Fantasy', 'Family', 'Music', 'Animation'],
 ['Comedy'],
 ['Action', 'Comedy', 'Thriller'],
 ['Drama', 'Comedy', 'Romance'],
 ['Drama', 'Thriller', 'Mystery'],
 ['Comedy', 'Romance', 'Drama'],
 ['Animation', 'Comedy', 'Family', 'Science Fiction'],
 ['Action', 'Crime', 'Science Fiction', 'Thriller'],
 ['Fantasy', 'Comedy', 'Family', 'Romance'],
 ['Thriller', 'Crime', 'Drama'],
 ['Romance', 'Comedy'],
 ['Action', 'Thriller', 'Crime'],
 ['Mystery', 'Thriller', 'Action'],
 ['Drama'],
 ['Action', 'Thriller', 'Science Fiction'],
 ['Comedy', 'Family', 'Science Fiction'],
 ['Horror', 'Thriller', 'Fantasy', 'Mystery'],
 ['Animation', 'Comedy', 'Drama', 'Family', 'Fantasy'],
 ['Action', 'Comedy', 'Crime', 'Mystery', 'Family'],
 ['Drama', 'Science Fiction', 'Thriller'],
 ['Action', 'Drama', 'Mystery', 'Thriller'],
 ['War', 'Drama', 'Action'],
 ['Action', 'Adventure', 'Comedy', 'Romance'],
 ['Comedy', 'Family', 'Animation', 'Adventure'],
 ['Western', 'Animation', 'Adventure', 'Comedy', 'Family'],
 ['Comedy', 'Romance', 'Family'],
 ['Adventure', 'Family', 'Science Fiction'],
 ['Drama', 'Thriller', 'Mystery'],
 ['Romance', 'Drama'],
 ['Animation', 'Comedy', 'Family'],
 ['Animation', 'Family', 'Music'],
 ['Science Fiction', 'Adventure', 'Action'],
 ['Action', 'Adventure', 'Family', 'Fantasy'],
 ['Action', 'Crime', 'Thriller'],
 ['Action', 'Adventure'],
 ['Drama', 'Fantasy', 'Romance'],
 ['Comedy', 'Fantasy', 'Romance'],
 ['Adventure', 'Fantasy', 'Action', 'Comedy', 'Thriller'],
 ['Comedy', 'Fantasy', 'Science Fiction'],
 ['Mystery', 'Drama', 'Horror'],
 ['Action', 'Adventure', 'Drama'],
 ['Action', 'Science Fiction', 'Thriller'],
 ['Drama', 'Thriller'],
 ['Action', 'Adventure', 'Thriller'],
 ['Animation', 'Family', 'Adventure'],
 ['Action', 'Science Fiction', 'War'],
 ['Animation', 'Comedy', 'Family'],
 ['Drama', 'Music', 'Romance'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Drama', 'Adventure'],
 ['Adventure', 'Comedy', 'Drama', 'Family', 'Fantasy'],
 ['Fantasy', 'Action', 'Adventure'],
 ['Thriller', 'Action', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Animation', 'Family'],
 ['Documentary', 'Family'],
 ['Thriller', 'Science Fiction', 'Adventure', 'Action'],
 ['Action', 'Adventure', 'History', 'Romance', 'Drama'],
 ['Comedy', 'Animation'],
 ['Drama', 'Romance'],
 ['Family', 'Animation', 'Drama'],
 ['Adventure', 'Action', 'Science Fiction'],

In [27]:
movies["genres"] = name_result

C:\Users\user\AppData\Local\Temp\ipykernel_37328\2446213483.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["genres"] = name_result

In [29]:
keyword_result = []

for keywords in movies["keywords"] :
    temp_list = []
    for keyword in keywords:
        temp_list.append(keyword["name"])
    keyword_result.append(temp_list)

movies["keywords"] = keyword_result

C:\Users\user\AppData\Local\Temp\ipykernel_37328\729920683.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["keywords"] = keyword_result

In [32]:
movies.head()

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",7.2,11800,150.437577,"[culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]","In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",6.9,4500,139.082615,"[ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems."
2,206647,Spectre,"[Action, Adventure, Crime]",6.3,4466,107.376788,"[spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]","A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",7.6,9106,112.312950,"[dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, cover-up, superhero, villainess, tragic hero, terrorism, destruction, catwoman, cat burglar, imax, flood, criminal underworld, batman]","Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a cit..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]",6.1,2124,43.926995,"[based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword and planet, 19th century, 3d]","John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands."

### CountVectorizer 사용

In [34]:
data_result = []

for genres in movies["genres"]:
    data = " ".join(genres)
    data_result.append(data)

movies["genres_literal"] = data_result

movies.genres_literal

C:\Users\user\AppData\Local\Temp\ipykernel_37328\1178161543.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["genres_literal"] = data_result

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801
4802                                 Documentary
Name: genres_literal, Length: 4803, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(min_df=1, ngram_range=(1,2)) #전체 문서에서 최소 한번 등장한 단어 추출, 한단어씩 먼저 만들고, 두개씩 묶어서도 만들어라 -> 한번 이상 등장해야 count

genres_vect = cv.fit_transform(movies['genres_literal'])

cv.vocabulary_

{'action': 0,
 'adventure': 16,
 'fantasy': 124,
 'science': 232,
 'fiction': 138,
 'action adventure': 1,
 'adventure fantasy': 24,
 'fantasy science': 135,
 'science fiction': 233,
 'fantasy action': 125,
 'crime': 64,
 'adventure crime': 20,
 'drama': 90,
 'thriller': 234,
 'action crime': 4,
 'crime drama': 68,
 'drama thriller': 106,
 'adventure science': 29,
 'animation': 33,
 'family': 109,
 'animation family': 38,
 'fantasy family': 130,
 'action science': 12,
 'adventure action': 17,
 'action thriller': 13,
 'thriller crime': 238,
 'western': 265,
 'adventure western': 32,
 'adventure family': 23,
 'family fantasy': 115,
 'fiction action': 139,
 'action fantasy': 7,
 'comedy': 44,
 'action comedy': 3,
 'comedy science': 59,
 'adventure drama': 22,
 'drama action': 91,
 'romance': 214,
 'drama romance': 104,
 'romance thriller': 228,
 'thriller action': 235,
 'fiction thriller': 150,
 'adventure thriller': 30,
 'fantasy adventure': 126,
 'family adventure': 111,
 'adventure comedy': 19,
 'thriller science': 247,
 'family comedy': 113,
 'horror': 170,
 'action drama': 5,
 'drama horror': 101,
 'horror science': 180,
 'action family': 6,
 'action romance': 11,
 'fiction adventure': 140,
 'adventure animation': 18,
 'animation adventure': 35,
 'comedy family': 51,
 'family action': 110,
 'comedy crime': 48,
 'crime thriller': 78,
 'animation drama': 37,
 'fiction fantasy': 146,
 'animation comedy': 36,
 'drama family': 97,
 'fiction western': 152,
 'crime fantasy': 70,
 'fantasy comedy': 128,
 'drama comedy': 94,
 'comedy animation': 47,
 'drama fantasy': 98,
 'fantasy drama': 129,
 'family romance': 120,
 'fiction romance': 149,
 'comedy adventure': 46,
 'fantasy animation': 127,
 'mystery': 200,
 'family mystery': 119,
 'mystery science': 210,
 'family animation': 112,
 'animation action': 34,
 'drama science': 105,
 'fiction mystery': 148,
 'mystery adventure': 202,
 'thriller mystery': 245,
 'mystery romance': 209,
 'comedy drama': 50,
 'thriller adventure': 236,
 'history': 158,
 'war': 252,
 'history romance': 166,
 'romance war': 230,
 'war history': 258,
 'history action': 159,
 'horror action': 171,
 'comedy fantasy': 52,
 'horror thriller': 181,
 'drama war': 107,
 'action animation': 2,
 'action war': 14,
 'action mystery': 10,
 'drama mystery': 103,
 'animation fantasy': 39,
 'western drama': 271,
 'drama adventure': 92,
 'family western': 123,
 'western adventure': 267,
 'mystery thriller': 211,
 'animation science': 42,
 'fiction family': 145,
 'comedy thriller': 60,
 'animation mystery': 41,
 'family science': 121,
 'crime mystery': 75,
 'fantasy horror': 131,
 'adventure mystery': 27,
 'action history': 8,
 'history war': 168,
 'thriller drama': 240,
 'drama history': 100,
 'war action': 253,
 'crime comedy': 67,
 'fiction drama': 144,
 'adventure history': 25,
 'music': 187,
 'romance family': 221,
 'animation music': 40,
 'comedy romance': 58,
 'history crime': 160,
 'drama crime': 95,
 'drama western': 108,
 'drama animation': 93,
 'thriller romance': 246,
 'horror mystery': 178,
 'romance fantasy': 222,
 'family drama': 114,
 'western history': 272,
 'mystery drama': 204,
 'thriller history': 242,
 'comedy action': 45,
 'thriller fantasy': 241,
 'fantasy thriller': 136,
 'romance science': 227,
 'history thriller': 167,
 'romance drama': 220,
 'fantasy romance': 134,
 'drama music': 102,
 'horror comedy': 172,
 'family music': 118,
 'music animation': 189,
 'crime science': 77,
 'romance comedy': 218,
 'fantasy mystery': 133,
 'mystery family': 205,
 'war drama': 257,
 'western animation': 268,
 'fiction war': 151,
 'music romance': 197,
 'documentary': 80,
 'documentary family': 85,
 'thriller horror': 243,
 'comedy music': 56,
 'crime romance': 76,
 'war science': 262,
 'thriller war': 248,
 'fantasy music': 132,
 'fantasy war': 137,
 'action horror': 9,
 'music family': 194,
 'mystery action': 201,
 'history drama': 162,
 'crime action': 65,
 'action western': 15,
 'mystery western': 213,
 'adventure war': 31,
 'music documentary': 192,
 'fiction horror': 147,
 'fiction animation': 141,
 'romance adventure': 216,
 'adventure horror': 26,
 'fiction comedy': 142,
 'comedy western': 63,
 'family thriller': 122,
 'crime adventure': 66,
 'crime family': 69,
 'horror romance': 179,
 'romance animation': 217,
 'comedy horror': 55,
 'horror fantasy': 176,
 'adventure romance': 28,
 'music drama': 193,
 'mystery war': 212,
 'romance western': 231,
 'history western': 169,
 'western thriller': 275,
 'romance action': 215,
 'romance horror': 225,
 'history mystery': 165,
 'comedy war': 62,
 'crime history': 72,
 'war adventure': 254,
 'war romance': 261,
 'western crime': 270,
 'crime horror': 73,
 'war crime': 256,
 'music comedy': 190,
 'romance history': 224,
 'mystery fantasy': 206,
 'romance crime': 219,
 'family horror': 117,
 'thriller music': 244,
 'war music': 259,
 'mystery crime': 203,
 'comedy documentary': 49,
 'documentary action': 81,
 'horror drama': 175,
 'music adventure': 188,
 'western music': 273,
 'romance music': 226,
 'foreign': 153,
 'drama foreign': 99,
 'thriller western': 249,
 'crime war': 79,
 'mystery horror': 207,
 'music crime': 191,
 'history music': 164,
 'war comedy': 255,
 'western action': 266,
 'horror crime': 173,
 'history family': 163,
 'thriller comedy': 237,
 'documentary music': 88,
 'crime music': 74,
 'comedy mystery': 57,
 'crime foreign': 71,
 'romance foreign': 223,
 'western romance': 274,
 'mystery music': 208,
 'foreign romance': 156,
 'foreign history': 155,
 'family foreign': 116,
 'music science': 198,
 'tv': 250,
 'movie': 182,
 'tv movie': 251,
 'movie romance': 186,
 'music mystery': 196,
 'fiction crime': 143,
 'war mystery': 260,
 'comedy foreign': 53,
 'documentary comedy': 82,
 'war thriller': 263,
 'movie crime': 184,
 'music tv': 199,
 'drama documentary': 96,
 'comedy history': 54,
 'romance tv': 229,
 'war western': 264,
 'movie horror': 185,
 'movie action': 183,
 'western comedy': 269,
 'documentary drama': 84,
 'animation war': 43,
 'history documentary': 161,
 'horror history': 177,
 'thriller documentary': 239,
 'documentary crime': 83,
 'horror documentary': 174,
 'documentary mystery': 89,
 'adventure documentary': 21,
 'documentary foreign': 86,
 'music horror': 195,
 'foreign documentary': 154,
 'comedy tv': 61,
 'documentary history': 87,
 'foreign thriller': 157}

In [41]:
print(genres_vect.shape)

print(genres_vect.toarray())

genre_vect_array = genres_vect.toarray()

(4803, 276)
[[1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [102]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_vect_array, genre_vect_array)

genre_sim_sorted = genre_sim.argsort(axis=1)[:, ::-1]

In [101]:
genre_sim

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(4803, 4803))

In [103]:
genre_sim_sorted[:10, :]

array([[   0,   46, 3494, ..., 3600, 3569, 4799],
       [   1,  129,   12, ..., 4754, 4753, 3829],
       [1740, 1542,    2, ..., 4757, 4758, 4795],
       ...,
       [  47, 2444, 3305, ..., 4789, 4788, 4786],
       [ 114,  191,  197, ...,   44,   45, 4784],
       [  19,   38, 2655, ...,   42,   34, 4784]], shape=(10, 4803))

In [99]:
def find_sim_movie(df , sorted_index, title_name, top_n=10):
    
    title_movie = df[df['title']==title_name]
    title_index = title_movie.index.values
    print(title_index)

    similar_index = sorted_index[title_index, : (top_n)]
    similar_index = similar_index.reshape(-1)

    return df.iloc[similar_index]

In [104]:
movie_result = find_sim_movie(movies, genre_sim_sorted, "Spectre", 10)
movie_result.title

[2]

1740         Kick-Ass 2
1542              Speed
2               Spectre
969           Assassins
873               Shaft
1615      Gridiron Gang
356     Sherlock Holmes
1076           Cellular
1058     Changing Lanes
1073     The River Wild
Name: title, dtype: object

## 협업필터링 (movie)

In [106]:
movie = pd.read_csv("../../data_resources/movie/movies.csv")
rating = pd.read_csv("../../data_resources/movie/ratings.csv")

In [116]:
df = pd.merge(movie, rating, on="movieId")

df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,3.0,851866703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9,4.0,938629179
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13,5.0,1331380058
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.0,997938310
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,3.0,855190091
...,...,...,...,...,...,...
99999,161944,The Last Brickmaker in America (2001),Drama,287,5.0,1470167824
100000,162376,Stranger Things,Drama,73,4.5,1474255532
100001,162542,Rustom (2016),Romance|Thriller,611,5.0,1471520667
100002,162672,Mohenjo Daro (2016),Adventure|Drama|Romance,611,3.0,1471523986
100003,163949,The Beatles: Eight Days a Week - The Touring Years (2016),Documentary,547,5.0,1476419239

In [113]:
df.movieId.nunique()

9066

In [121]:
title_user = df.pivot_table(index="userId", columns="title", values="rating")
title_user

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
title_user.iloc[0].sort_values(ascending=False)

title
French Connection, The (1971)                     4.0
Tron (1982)                                       4.0
Cinema Paradiso (Nuovo cinema Paradiso) (1989)    4.0
Dracula (Bram Stoker's Dracula) (1992)            3.5
Gods Must Be Crazy, The (1980)                    3.0
                                                 ...
xXx (2002)                                        NaN
xXx: State of the Union (2005)                    NaN
¡Three Amigos! (1986)                             NaN
À nous la liberté (Freedom for Us) (1931)         NaN
İtirazım Var (2014)                               NaN
Name: 1, Length: 9064, dtype: float64

In [124]:
title_user = title_user.fillna(0.0)

In [126]:
pd.set_option("display.max_columns", None)

In [127]:
title_user

title   "Great Performances" Cats (1998)  $9.99 (2008)  \
userId
1                                    0.0           0.0
2                                    0.0           0.0
3                                    0.0           0.0
4                                    0.0           0.0
5                                    0.0           0.0
...                                  ...           ...
667                                  0.0           0.0
668                                  0.0           0.0
669                                  0.0           0.0
670                                  0.0           0.0
671                                  0.0           0.0

title   'Hellboy': The Seeds of Creation (2004)  \
userId
1                                           0.0
2                                           0.0
3                                           0.0
4                                           0.0
5                                           0.0
...                                         ...
667                                         0.0
668                                         0.0
669                                         0.0
670                                         0.0
671                                         0.0

title   'Neath the Arizona Skies (1934)  'Round Midnight (1986)  \
userId
1                                   0.0                     0.0
2                                   0.0                     0.0
3                                   0.0                     0.0
4                                   0.0                     0.0
5                                   0.0                     0.0
...                                 ...                     ...
667                                 0.0                     0.0
668                                 0.0                     0.0
669                                 0.0                     0.0
670                                 0.0                     0.0
671                                 0.0                     0.0

title   'Salem's Lot (2004)  'Til There Was You (1997)  'burbs, The (1989)  \
userId
1                       0.0                        0.0                 0.0
2                       0.0                        0.0                 0.0
3                       0.0                        0.0                 0.0
4                       0.0                        0.0                 0.0
5                       0.0                        0.0                 0.0
...                     ...                        ...                 ...
667                     0.0                        0.0                 0.0
668                     0.0                        0.0                 0.0
669                     0.0                        0.0                 0.0
670                     0.0                        0.0                 0.0
671                     0.0                        0.0                 0.0

title   'night Mother (1986)  (500) Days of Summer (2009)  \
userId
1                        0.0                          0.0
2                        0.0                          0.0
3                        0.0                          0.0
4                        0.0                          0.0
5                        0.0                          0.0
...                      ...                          ...
667                      0.0                          0.0
668                      0.0                          0.0
669                      0.0                          0.0
670                      0.0                          0.0
671                      0.0                          0.0

title   *batteries not included (1987)  ...And God Spoke (1993)  \
userId
1                                  0.0                      0.0
2                                  0.0                      0.0
3                                  0.0                      0.0
4                                  0.0                      0.0
5                                  0.0                      0.0
...                                ...                      ...
667                                0.0                      0.0
668                                0.0                      0.0
669                                0.0                      0.0
670                                0.0                      0.0
671                                0.0                      0.0

title   ...And Justice for All (1979)  1-900 (06) (1994)  10 (1979)  \
userId
1                                 0.0                0.0        0.0
2                                 0.0                0.0        0.0
3                                 0.0                0.0        0.0
4                                 0.0                0.0        0.0
5                                 0.0                0.0        0.0
...                               ...                ...        ...
667                               0.0                0.0        0.0
668                               0.0                0.0        0.0
669                               0.0                0.0        0.0
670                               0.0                0.0        0.0
671                               0.0                0.0        0.0

title   10 Attitudes (2001)  10 Cloverfield Lane (2016)  \
userId
1                       0.0                         0.0
2                       0.0                         0.0
3                       0.0                         0.0
4                       0.0                         0.0
5                       0.0                         0.0
...                     ...                         ...
667                     0.0                         0.0
668                     0.0                         0.0
669                     0.0                         0.0
670                     0.0                         0.0
671                     0.0                         0.0

title   10 Items or Less (2006)  10 Things I Hate About You (1999)  \
userId
1                           0.0                                0.0
2                           0.0                                0.0
3                           0.0                                0.0
4                           0.0                                0.0
5                           0.0                                0.0
...                         ...                                ...
667                         0.0                                0.0
668                         0.0                                0.0
669                         0.0                                0.0
670                         0.0                                0.0
671                         0.0                                0.0

title   10 Years (2011)  10,000 BC (2008)  100 Girls (2000)  \
userId
1                   0.0               0.0               0.0
2                   0.0               0.0               0.0
3                   0.0               0.0               0.0
4                   0.0               0.0               0.0
5                   0.0               0.0               0.0
...                 ...               ...               ...
667                 0.0               0.0               0.0
668                 0.0               0.0               0.0
669                 0.0               0.0               0.0
670                 0.0               0.0               0.0
671                 0.0               0.0               0.0

title   100 Rifles (1969)  101 Dalmatians (1996)  \
userId
1                     0.0                    0.0
2                     0.0                    0.0
3                     0.0                    0.0
4                     0.0                    0.0
5                     0.0                    0.0
...                   ...                    ...
667                   0.0                    0.0
668                   0.0                    0.0
669                   0.0                    0.0
670                   0.0                    0.0
671                   0.0                    0.0

title   101 Dalmatians (One Hundred and One Dalmatians) (1961)  \
userId
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          5.0
5                                                          0.0
...                                                        ...
667                                                        0.0
668                                                        0.0
669                                                        0.0
670                                                        0.0
671                                                        0.0

title   101 Reykjavik (101 Reykjavík) (2000)  102 Dalmatians (2000)  \
userId
1                                        0.0                    0.0
2                                        0.0                    0.0
3                                        0.0                    0.0
4                                        0.0                    0.0
5                                        0.0                    0.0
...                                      ...                    ...
667                                      0.0                    0.0
668                                      0.0                    0.0
669                                      0.0                    0.0
670                                      0.0                    0.0
671                                      0.0                    0.0

title   10th Kingdom, The (2000)  11'09"01 - September 11 (2002)  \
userId
1                            0.0                             0.0
2                            0.0                             0.0
3                            0.0                             0.0
4                            0.0                             0.0
5                            0.0                             0.0
...                          ...                             ...
667                          0.0                             0.0
668                          0.0                             0.0
669                          0.0                             0.0
670                          0.0                             0.0
671                          0.0                             0.0

title   11:14 (2003)  12 Angry Men (1957)  12 Angry Men (1997)  \
userId
1                0.0                  0.0                  0.0
2                0.0                  0.0                  0.0
3                0.0                  0.0                  0.0
4                0.0                  0.0                  0.0
5                0.0                  0.0                  0.0
...              ...                  ...                  ...
667              0.0                  0.0                  0.0
668              0.0                  0.0                  0.0
669              0.0                  0.0                  0.0
670              0.0                  0.0                  0.0
671              0.0                  0.0                  0.0

title   12 Years a Slave (2013)  127 Hours (2010)  \
userId
1                           0.0               0.0
2                           0.0               0.0
3                           0.0               0.0
4                           0.0               0.0
5                           0.0               0.0
...                         ...               ...
667                         0.0               0.0
668                         0.0               0.0
669                         0.0               0.0
670                         0.0               0.0
671                         0.0               0.0

title   12:08 East of Bucharest (A fost sau n-a fost?) (2006)  \
userId
1                                                         0.0
2                                                         0.0
3                                                         0.0
4                                                         0.0
5                                                         0.0
...                                                       ...
667                                                       0.0
668                                                       0.0
669                                                       0.0
670                                                       0.0
671                                                       0.0

title   13 Assassins (Jûsan-nin no shikaku) (2010)  13 Ghosts (1960)  \
userId
1                                              0.0               0.0
2                                              0.0               0.0
3                                              0.0               0.0
4                                              0.0               0.0
5                                              0.0               0.0
...                                            ...               ...
667                                            0.0               0.0
668                                            0.0               0.0
669                                            0.0               0.0
670                                            0.0               0.0
671                                            0.0               0.0

title   13 Going on 30 (2004)  13 Tzameti (2005)  13th Warrior, The (1999)  \
userId
1                         0.0                0.0                       0.0
2                         0.0                0.0                       0.0
3                         0.0                0.0                       0.0
4                         0.0                0.0                       0.0
5                         0.0                0.0                       0.0
...                       ...                ...                       ...
667                       0.0                0.0                       0.0
668                       0.0                0.0                       0.0
669                       0.0                0.0                       0.0
670                       0.0                0.0                       0.0
671                       0.0                0.0                       0.0

title   1408 (2007)  15 Minutes (2001)  16 Blocks (2006)  16 Wishes (2010)  \
userId
1               0.0                0.0               0.0               0.0
2               0.0                0.0               0.0               0.0
3               0.0                0.0               0.0               0.0
4               0.0                0.0               0.0               0.0
5               0.0                0.0               0.0               0.0
...             ...                ...               ...               ...
667             0.0                0.0               0.0               0.0
668             0.0                0.0               0.0               0.0
669             0.0                0.0               0.0               0.0
670             0.0                0.0               0.0               0.0
671             0.0                0.0               0.0               0.0

title   17 Again (2009)  18 Again! (1988)  187 (One Eight Seven) (1997)  \
userId
1                   0.0               0.0                           0.0
2                   0.0               0.0                           0.0
3                   0.0               0.0                           0.0
4                   0.0               0.0                           0.0
5                   0.0               0.0                           0.0
...                 ...               ...                           ...
667                 0.0               0.0                           0.0
668                 0.0               0.0                           0.0
669                 0.0               0.0                           0.0
670                 0.0               0.0                           0.0
671                 0.0               0.0                           0.0

title   1941 (1979)  1984 (1956)  1984 (Nineteen Eighty-Four) (1984)  \
userId
1               0.0          0.0                                 0.0
2               0.0          0.0                                 0.0
3               0.0          0.0                                 0.0
4               0.0          0.0                                 0.0
5               0.0          0.0                                 0.0
...             ...          ...                                 ...
667             0.0          0.0                                 0.0
668             0.0          0.0                                 0.0
669             0.0          0.0                                 0.0
670             0.0          0.0                                 0.0
671             0.0          0.0                                 0.0

title   1990: The Bronx Warriors (1990: I guerrieri del Bronx) (1982)  \
userId
1                                                                 0.0
2                                                                 0.0
3                                                                 0.0
4                                                                 0.0
5                                                                 0.0
...                                                               ...
667                                                               0.0
668                                                               0.0
669                                                               0.0
670                                                               0.0
671                                                               0.0

title   2 Days in New York (2012)  2 Days in the Valley (1996)  \
userId
1                             0.0                          0.0
2                             0.0                          0.0
3                             0.0                          0.0
4                             0.0                          0.0
5                             0.0                          0.0
...                           ...                          ...
667                           0.0                          0.0
668                           0.0                          0.0
669                           0.0                          0.0
670                           0.0                          0.0
671                           0.0                          0.0

title   2 Fast 2 Furious (Fast and the Furious 2, The) (2003)  2 Guns (2013)  \
userId
1                                                         0.0            0.0
2                                                         0.0            0.0
3                                                         0.0            0.0
4                                                         0.0            0.0
5                                                         0.0            0.0
...                                                       ...            ...
667                                                       0.0            0.0
668                                                       0.0            0.0
669                                                       0.0            0.0
670                                                       0.0            0.0
671                                                       0.0            0.0

title   2 ou 3 choses que je sais d'elle (2 or 3 Things I Know About Her) (1967)  \
userId
1                                                                            0.0
2                                                                            0.0
3                                                                            0.0
4                                                                            0.0

In [129]:
pd.reset_option("display.max_columns", None)

In [135]:
user_based_result = cosine_similarity(title_user, title_user)

user_based_df =pd.DataFrame(user_based_result, index=title_user.index, columns=title_user.index)
user_based_df

userId,1,2,3,4,5,6,7,8,9,10,...,662,663,664,665,666,667,668,669,670,671
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.000000,0.000000,0.074482,0.016818,0.000000,0.083884,0.000000,0.012843,0.000000,...,0.000000,0.000000,0.014481,0.043719,0.000000,0.000000,0.000000,0.062917,0.000000,0.017466
2,0.000000,1.000000,0.124295,0.118821,0.103646,0.000000,0.212985,0.113190,0.113333,0.043213,...,0.477306,0.063202,0.077784,0.164162,0.466281,0.425462,0.084646,0.024140,0.170595,0.113175
3,0.000000,0.124295,1.000000,0.081640,0.151531,0.060691,0.154714,0.249781,0.134475,0.114672,...,0.161205,0.064198,0.176222,0.158357,0.177098,0.124562,0.124911,0.080984,0.136606,0.170193
4,0.074482,0.118821,0.081640,1.000000,0.130649,0.079648,0.319745,0.191013,0.030417,0.137186,...,0.114319,0.047228,0.136647,0.254030,0.121905,0.088735,0.068483,0.104309,0.054512,0.211609
5,0.016818,0.103646,0.151531,0.130649,1.000000,0.063796,0.095888,0.165712,0.086616,0.032370,...,0.191029,0.021142,0.146246,0.224245,0.139721,0.058252,0.042926,0.038358,0.062642,0.225086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.000000,0.425462,0.124562,0.088735,0.058252,0.000000,0.232051,0.069005,0.066412,0.032653,...,0.342283,0.050754,0.074118,0.124214,0.351207,1.000000,0.091597,0.018416,0.153111,0.127995
668,0.000000,0.084646,0.124911,0.068483,0.042926,0.019563,0.058773,0.112366,0.194493,0.098561,...,0.074089,0.059010,0.093068,0.082525,0.114487,0.091597,1.000000,0.000000,0.178017,0.135387
669,0.062917,0.024140,0.080984,0.104309,0.038358,0.024583,0.073151,0.055143,0.029291,0.060549,...,0.015960,0.025953,0.077966,0.101707,0.028773,0.018416,0.000000,1.000000,0.042609,0.085202
670,0.000000,0.170595,0.136606,0.054512,0.062642,0.019465,0.096240,0.247687,0.384429,0.158650,...,0.183662,0.122126,0.123469,0.143380,0.159479,0.153111,0.178017,0.042609,1.000000,0.228677
671,0.017466,0.113175,0.170193,0.211609,0.225086,0.087705,0.268672,0.406414,0.168497,0.189703,...,0.096704,0.070749,0.219839,0.239318,0.127204,0.127995,0.135387,0.085202,0.228677,1.000000

In [139]:
user_based_df.iloc[0].sort_values(ascending=False)[1:6]

userId
325    0.371852
634    0.194093
341    0.162819
310    0.157524
207    0.152746
Name: 1, dtype: float64

In [149]:
print(title_user.iloc[0].index[0])

"Great Performances" Cats (1998)

In [146]:
title_user.iloc[0].sort_values(ascending=False)

my_list = []

for index, rating in enumerate(title_user.iloc[0]):
    if rating > 0:
        my_list.append(title_user.iloc[0].index[index])

print('0번 유저가 본 영화의 갯수:', len(my_list))

my_list

0번 유저가 본 영화의 갯수: 20

['Antz (1998)',
 'Beavis and Butt-Head Do America (1996)',
 'Ben-Hur (1959)',
 'Blazing Saddles (1974)',
 'Cape Fear (1991)',
 'Cinema Paradiso (Nuovo cinema Paradiso) (1989)',
 'Dangerous Minds (1995)',
 'Deer Hunter, The (1978)',
 "Dracula (Bram Stoker's Dracula) (1992)",
 'Dumbo (1941)',
 'Escape from New York (1981)',
 'Fly, The (1986)',
 'French Connection, The (1971)',
 'Gandhi (1982)',
 'Gods Must Be Crazy, The (1980)',
 'Sleepers (1996)',
 'Star Trek: The Motion Picture (1979)',
 'Time Bandits (1981)',
 'Tron (1982)',
 'Willow (1988)']

In [155]:
u_data = title_user.loc[325]
u_list = u_data[u_data >= 4].index

In [156]:
set(u_list) - set(my_list)

{'Beverly Hills Cop (1984)',
 'Brady Bunch Movie, The (1995)',
 "My Best Friend's Wedding (1997)"}