# Surprise 라이브러리를 활용한 협업필터링(아이템기반)

In [31]:
import pandas as pd
import numpy as np

In [32]:
movie = pd.read_csv("../../data_resources/movie/movies.csv")
rating = pd.read_csv("../../data_resources/movie/ratings.csv")

In [33]:
df = pd.merge(movie, rating, on="movieId")

df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,3.0,851866703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9,4.0,938629179
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13,5.0,1331380058
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.0,997938310
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,3.0,855190091
...,...,...,...,...,...,...
99999,161944,The Last Brickmaker in America (2001),Drama,287,5.0,1470167824
100000,162376,Stranger Things,Drama,73,4.5,1474255532
100001,162542,Rustom (2016),Romance|Thriller,611,5.0,1471520667
100002,162672,Mohenjo Daro (2016),Adventure|Drama|Romance,611,3.0,1471523986
100003,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,547,5.0,1476419239

In [49]:
title_user = df.pivot_table(index="userId", columns="title", values="rating")
title_user
title_user.fillna(0, inplace=True)

rating_matrix = title_user.T

rating_matrix

userId,1,2,3,4,5,6,7,8,9,10,...,662,663,664,665,666,667,668,669,670,671
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$9.99 (2008),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Neath the Arizona Skies (1934),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
¡Three Amigos! (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
İtirazım Var (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
from sklearn.metrics.pairwise import cosine_similarity
item_sim = cosine_similarity(rating_matrix, rating_matrix)

item_sim_df = pd.DataFrame(data=item_sim, index=rating_matrix.index, columns=rating_matrix.index)
item_sim_df

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",1.000000,0.000000,0.0,0.164399,0.020391,0.0,0.014046,0.000000,0.000000,0.003166,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0000
$9.99 (2008),0.000000,1.000000,0.0,0.000000,0.000000,0.0,0.000000,0.079474,0.000000,0.156330,...,0.000000,0.000000,0.0,0.000000,0.0,0.013899,0.000000,0.058218,0.0,0.0000
'Hellboy': The Seeds of Creation (2004),0.000000,0.000000,1.0,0.000000,0.000000,1.0,0.000000,0.217357,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0000
'Neath the Arizona Skies (1934),0.164399,0.000000,0.0,1.000000,0.124035,0.0,0.085436,0.000000,0.000000,0.019259,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0000
'Round Midnight (1986),0.020391,0.000000,0.0,0.124035,1.000000,0.0,0.010597,0.143786,0.000000,0.136163,...,0.000000,0.000000,0.0,0.121567,0.0,0.000000,0.000000,0.000000,0.0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx (2002),0.000000,0.013899,0.0,0.000000,0.000000,0.0,0.000000,0.123940,0.000000,0.144961,...,0.161281,0.076029,0.0,0.017465,0.0,1.000000,0.152057,0.140222,0.0,0.2661
xXx: State of the Union (2005),0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.134815,...,0.000000,0.000000,0.0,0.000000,0.0,0.152057,1.000000,0.000000,0.0,0.0000
¡Three Amigos! (1986),0.000000,0.058218,0.0,0.000000,0.000000,0.0,0.081620,0.331663,0.214498,0.064908,...,0.112588,0.159223,0.0,0.166622,0.0,0.140222,0.000000,1.000000,0.0,0.0000
À nous la liberté (Freedom for Us) (1931),0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.0,0.0000
İtirazım Var (2014),0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.134815,...,0.000000,0.000000,0.0,0.000000,0.0,0.266100,0.000000,0.000000,0.0,1.0000

In [36]:
item_sim_df["Toy Story (1995)"].sort_values(ascending=False)[1:6]

title
Toy Story 2 (1999)                           0.428382
Star Wars: Episode IV - A New Hope (1977)    0.414637
Independence Day (a.k.a. ID4) (1996)         0.407789
Forrest Gump (1994)                          0.385906
Groundhog Day (1993)                         0.382651
Name: Toy Story (1995), dtype: float64

In [37]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split
from surprise import Reader
from surprise.dataset import DatasetAutoFolds
import pandas as pd

In [38]:
ratings = pd.read_csv("../../data_resources/movie/ratings.csv")
ratings

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [39]:
ratings.to_csv("../../data_resources/movie/ratings_nohead.csv", index=False, header=False)

In [40]:
ratings.describe()
ratings.rating.unique()

array([2.5, 3. , 2. , 4. , 3.5, 1. , 5. , 4.5, 1.5, 0.5])

In [41]:
reader = Reader(line_format="user item rating timestamp", sep=",", rating_scale=(0.5, 5))

data_folds = DatasetAutoFolds(ratings_file="../../data_resources/movie/ratings_nohead.csv", reader=reader)

trainset = data_folds.build_full_trainset() # 모든 데이터를 다 학습 셋으로 쓰겠다.

svd = SVD(n_factors=50, random_state=42) # 행렬분해 모델 #50차원의 특성을 뽑아내서 학습에 쓰겠다.

svd.fit(trainset)

In [42]:
trainset

In [43]:
y_pred= svd.predict('9', '3')
y_pred

Prediction(uid='9', iid='3', r_ui=None, est=3.092324541202098, details={'was_impossible': False})

In [44]:
movies = pd.read_csv("../../data_resources/movie/movies.csv")
movies.head()
ratings = pd.read_csv("../../data_resources/movie/ratings.csv")
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [45]:
user9_movies = set(ratings[ratings["userId"] == 9]['movieId'])
user9_movies
whole_movie = set(movies['movieId'])

whole_movie - user9_movies

{2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 27,
 28,
 29,
 30,
 31,
 32,
 32797,
 34,
 35,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 48,
 49,
 50,
 65585,
 52,
 53,
 54,
 55,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 65601,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 32840,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 32853,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 65638,
 107,
 108,
 65642,
 110,
 111,
 112,
 113,
 114,
 32882,
 116,
 117,
 118,
 119,
 121,
 122,
 123,
 124,
 125,
 126,
 32892,
 129,
 130,
 131,
 132,
 32898,
 65665,
 135,
 137,
 98441,
 140,
 141,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 32943,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 98491,
 193,
 194,
 195,
 196,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 211,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 222,
 223,
 224,
 225,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 98585,
 285,
 98587,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 98607,
 98611,
 312,
 313,
 314,
 315,
 316,
 317,
 319,
 320,
 321,
 322,
 33085,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 33124,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 33145,
 33154,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 33158,
 33162,
 33164,
 33166,
 401,
 33171,
 405,
 407,
 408,
 409,
 410,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 498,
 499,
 500,
 501,
 502,
 98803,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 98829,
 526,
 528,
 529,
 33296,
 531,
 532,
 533,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 33312,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 66090,
 558,
 559,
 561,
 562,
 563,
 564,
 565,
 66097,
 567,
 568,
 569,
 571,
 573,
 574,
 575,
 577,
 580,
 581,
 582,
 585,
 586,
 587,
 588,
 589,
 590,
 33358,
 592,
 594,
 595,
 596,
 597,
 66130,
 599,
 600,
 603,
 98908,
 605,
 606,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 33380,
 619,
 620,
 621,
 626,
 627,
 628,
 98933,
 630,
 631,
 632,
 633,
 635,
 66171,
 637,
 638,
 639,
 640,
 131714,
 647,
 648,
 650,
 651,
 131724,
 653,
 656,
 98961,
 659,
 98963,
 661,
 662,
 663,
 664,
 665,
 66198,
 667,
 668,
 33437,
 670,
 671,
 66200,
 673,
 674,
 66203,
 678,
 679,
 680,
 681,
 685,
 687,
 688,
 690,
 691,
 692,
 694,
 695,
 696,
 697,
 698,
 700,
 99005,
 702,
 703,
 704,
 705,
 99007,
 707,
 708,
 709,
 710,
 711,
 66246,
 714,
 715,
 718,
 719,
 720,
 721,
 722,
 724,
 725,
 726,
 33493,
 728,
 33495,
 99030,
 731,
 33499,
 735,
 736,
 737,
 741,
 742,
 743,
 745,
 746,
 747,
 748,
 750,
 753,
 754,
 755,
 756,
 757,
 131830,
 759,
 760,
 761,
 762,
 66297,
 764,
 765,
 766,
 767,
 769,
 66310,
 775,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 66317,
 33558,
 99089,
 793,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 66335,
 808,
 809,
 810,
 99106,
 99112,
 813,
 99114,
 99117,
 816,
 818,
 33587,
 820,
 824,
 33592,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 66371,
 844,
 845,
 846,
 33615,
 848,
 849,
 850,
 851,
 852,
 33621,
 854,
 858,
 861,
 864,
 865,
 866,
 867,
 869,
 870,
 33639,
 872,
 875,
 876,
 33646,
 879,
 880,
 881,
 882,
 885,
 886,
 888,
 889,
 891,
 892,
 893,
 33660,
 66427,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 33688,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 99270,
 968,
 969,
 970,
 971,
 972,
 973,
 66509,
 99273,
 976,
 99276,
 132046,
 980,
 981,
 982,
 33750,
 984,
 986,
 987,
 988,
 990,
 991,
 992,
 33760,
 994,
 99296,
 996,
 997,
 998,
 999,
 132074,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1040,
 1041,
 1042,
 1043,
 1044,
 1046,
 1047,
 1049,
 1050,
 1051,
 33817,
 1053,
 1054,
 1055,
 1056,
 1057,
 33826,
 1060,
 1061,
 33830,
 1063,
 1064,
 66596,
 1066,
 1067,
 1068,
 1069,
 33834,
 33836,
 33838,
 1073,
 132146,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1099,
 1100,
 1101,
 1103,
 1104,
 1105,
 1111,
 1112,
 1113,
 1114,
 33880,
 99415,
 1120,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 33896,
 1135,
 1136,
 1137,
 33903,
 99437,
 164977,
 164979,
 33912,
 ...}

In [46]:
def get_unseen_movies(userId):
    return list(set(movies['movieId']) - set(ratings[ratings['userId'] == userId]['movieId']))

unseen_movies = get_unseen_movies(34)
len(unseen_movies)

8938

In [47]:
pred_result = []
userId = 34
for movieId in unseen_movies:
    result = svd.predict( str(userId), str(movieId) )

    temp_dict = {}
    temp_dict["id"] = result.iid
    temp_dict["est_rating"] = result.est
    temp_dict["title"] = movies[movies['movieId'] == int(result.iid)]['title'].iloc[0]

    pred_result.append(temp_dict)

result_df = pd.DataFrame(pred_result)
result_df.sort_values(by="est_rating", ascending=False, inplace=True)
# pred_result.sort(key=lambda x: x['est_rating'], reverse=True)
# pred_result[:10]
result_df[:5]

        id  est_rating                     title
2448  2959    4.641464         Fight Club (1999)
779    926    4.588059      All About Eve (1950)
1570  1945    4.516211  On the Waterfront (1954)
5671  7502    4.497760   Band of Brothers (2001)
1007  1217    4.477967                Ran (1985)

In [ ]:
result_df[:5]

        id  est_rating                     title
2448  2959    4.641464         Fight Club (1999)
779    926    4.588059      All About Eve (1950)
1570  1945    4.516211  On the Waterfront (1954)
5671  7502    4.497760   Band of Brothers (2001)
1007  1217    4.477967                Ran (1985)