## 가로수길과 성수 19~ 25년도 유동인구 변화를 주목한다

In [12]:
##유동인구 데이터 불러오기 
import pandas as pd

data = pd.read_csv("../data/서울시 상권분석서비스(길단위인구-상권).csv", encoding='cp949')
data

data.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20251,U,관광특구,3001496,강남 마이스 관광특구,100649,49922,50727,7069,20015,...,25342,20967,5110,14344,15196,15603,16864,16517,11758,10364
1,20251,U,관광특구,3001495,잠실 관광특구,4111537,1965328,2146209,427780,940714,...,657648,892677,483424,567968,565945,571332,585964,610821,633585,575923
2,20251,U,관광특구,3001494,종로?청계 관광특구,8147936,4304865,3843069,329308,1502435,...,1732364,1610382,642889,1232214,1266236,1237661,1298328,1323789,1046011,743696
3,20251,U,관광특구,3001493,동대문패션타운 관광특구,3304504,1540376,1764127,175313,630426,...,526153,637103,392709,505977,514359,503640,519249,504092,385614,371573
4,20251,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,6931325,3333639,3597687,320273,1208624,...,1710008,1314562,343316,1067275,1115314,1076686,1139517,1159683,793391,579458

In [13]:
sungsu_df = data[data["상권_코드_명"].str.contains("성수", na=False) ]
pd.set_option('display.max_rows', None)
sungsu_df[["상권_코드_명", "총_유동인구_수", "기준_년분기_코드"]]

          상권_코드_명  총_유동인구_수  기준_년분기_코드
256    성수역 골목형상점가     51277      20251
365        성수대교남단    795848      20251
508           성수역   1335392      20251
1513       성수초등학교   1660825      20251
1516    성수119안전센터   1533678      20251
1518   성수2가3동주민센터    477087      20251
1519      성수동카페거리   1001989      20251
1523   성수1가1동주민센터    172010      20251
1906   성수역 골목형상점가     52705      20244
2015       성수대교남단    820281      20244
2158          성수역   1418431      20244
3162       성수초등학교   1650174      20244
3165    성수119안전센터   1519674      20244
3167   성수2가3동주민센터    562403      20244
3168      성수동카페거리   1051943      20244
3172   성수1가1동주민센터    166119      20244
3555   성수역 골목형상점가     50991      20243
3664       성수대교남단    823278      20243
3807          성수역   1383668      20243
4810       성수초등학교   1594847      20243
4813    성수119안전센터   1575643      20243
4815   성수2가3동주민센터    558051      20243
4816      성수동카페거리    915300      20243
4820   성수1가1동주민센터    160631      20243
5203   성수역 골목형상점가     51897      20242
5312       성수대교남단    834613      20242
5455          성수역   1412970      20242
6459       성수초등학교   1533597      20242
6462    성수119안전센터   1664586      20242
6464   성수2가3동주민센터    548027      20242
6465      성수동카페거리    916677      20242
6469   성수1가1동주민센터    162195      20242
6852   성수역 골목형상점가     52891      20241
6961       성수대교남단    822907      20241
7104          성수역   1421488      20241
8108       성수초등학교   1493217      20241
8111    성수119안전센터   1622484      20241
8113   성수2가3동주민센터    578194      20241
8114      성수동카페거리    820123      20241
8118   성수1가1동주민센터    158303      20241
8501   성수역 골목형상점가     45408      20234
8610       성수대교남단    858299      20234
8753          성수역   1418127      20234
9756       성수초등학교   1490227      20234
9759    성수119안전센터   1525262      20234
9761   성수2가3동주민센터    517141      20234
9762      성수동카페거리    835450      20234
9766   성수1가1동주민센터    162424      20234
10149  성수역 골목형상점가     44018      20233
10258      성수대교남단    973892      20233
10401         성수역   1387647      20233
11405      성수초등학교   1485615      20233
11408   성수119안전센터   1423013      20233
11410  성수2가3동주민센터    486949      20233
11411     성수동카페거리    824579      20233
11415  성수1가1동주민센터    157495      20233
11798  성수역 골목형상점가     42980      20232
11907      성수대교남단   1000225      20232
12050         성수역   1426481      20232
13054      성수초등학교   1551078      20232
13057   성수119안전센터   1408138      20232
13059  성수2가3동주민센터    529716      20232
13060     성수동카페거리    846142      20232
13064  성수1가1동주민센터    172951      20232
13447  성수역 골목형상점가     42977      20231
13556      성수대교남단   1056750      20231
13699         성수역   1417339      20231
14703      성수초등학교   1548398      20231
14706   성수119안전센터   1437923      20231
14708  성수2가3동주민센터    547163      20231
14709     성수동카페거리    828038      20231
14713  성수1가1동주민센터    189107      20231
15096  성수역 골목형상점가     45152      20224
15205      성수대교남단   1031933      20224
15348         성수역   1401866      20224
16352      성수초등학교   1548966      20224
16355   성수119안전센터   1429978      20224
16357  성수2가3동주민센터    535109      20224
16358     성수동카페거리    811773      20224
16362  성수1가1동주민센터    177237      20224
16745  성수역 골목형상점가     44039      20223
16854      성수대교남단   1043527      20223
16997         성수역   1373427      20223
18002      성수초등학교   1502012      20223
18005   성수119안전센터   1438036      20223
18007  성수2가3동주민센터    501262      20223
18008     성수동카페거리    776493      20223
18012  성수1가1동주민센터    141592      20223
18395  성수역 골목형상점가     42676      20222
18504      성수대교남단    956749      20222
18647         성수역   1386093      20222
19652      성수초등학교   1468893      20222
19655   성수119안전센터   1488632      20222
19657  성수2가3동주민센터    555857      20222
19658     성수동카페거리    756083      20222
19662  성수1가1동주민센터    152448      20222
20045  성수역 골목형상점가     36725      20221
20154      성수대교남단    824979      20221
20297         성수역   1301597      20221
21302      성수초등학교   1413716      20221
21305   성수119안전센터   1485664      20221
21307  성수2가3동주민센터    622662      20221
21308     성수동카페거리    744737      20221
21312  성수1가1동주민센터    152035      20221
21695  성수역 골목형상점가     38315      20214
21804      성수대교남단    890899      20214
21947         성수역   1333319      20214
22952      성수초등학교   1397441      20214
22955   성수119안전센터   1501879      20214
22957  성수2가3동주민센터    589914      20214
22958     성수동카페거리    830886      20214
22962  성수1가1동주민센터    158788      20214
23345  성수역 골목형상점가     36270      20213
23454      성수대교남단    825977      20213
23597         성수역   1260955      20213
24602      성수초등학교   1324688      20213
24605   성수119안전센터   1555954      20213
24607  성수2가3동주민센터    612906      20213
24608     성수동카페거리    818858      20213
24612  성수1가1동주민센터    145550      20213
24995  성수역 골목형상점가     39534      20212
25104      성수대교남단    862692      20212
25247         성수역   1311262      20212
26252      성수초등학교   1346623      20212
26255   성수119안전센터   1795416      20212
26257  성수2가3동주민센터    692218      20212
26258     성수동카페거리    976976      20212
26262  성수1가1동주민센터    143185      20212
26645  성수역 골목형상점가     38749      20211
26754      성수대교남단    825667      20211
26897         성수역   1250905      20211
27902      성수초등학교   1282911      20211
27905   성수119안전센터   1816122      20211
27907  성수2가3동주민센터    712185      20211
27908     성수동카페거리    898642      20211
27912  성수1가1동주민센터    136470      20211
28295  성수역 골목형상점가     37074      20204
28404      성수대교남단    871068      20204
28547         성수역   1234342      20204
29552      성수초등학교   1246312      20204
29555   성수119안전센터   1847355      20204
29557  성수2가3동주민센터    714367      20204
29558     성수동카페거리    870230      20204
29562  성수1가1동주민센터    135315      20204
29945  성수역 골목형상점가     38027      20203
30054      성수대교남단    921421      20203
30197         성수역   1265466      20203
31202      성수초등학교   1232826      20203
31205   성수119안전센터   1944510      20203
31207  성수2가3동주민센터    715012      20203
31208     성수동카페거리    912903      20203
31212  성수1가1동주민센터    133067      20203
31595  성수역 골목형상점가     38211      20202
31704      성수대교남단    953415      20202
31847         성수역   1267124      20202
32852      성수초등학교   1068178      20202
32855   성수119안전센터   2047379      20202
32857  성수2가3동주민센터    716277      20202
32858     성수동카페거리    926634      20202
32862  성수1가1동주민센터    131481      20202
33245  성수역 골목형상점가     33093      20201
33354      성수대교남단    962164      20201
33497         성수역   1313441      20201
34502      성수초등학교   1676235      20201
34505   성수119안전센터   1907816      20201
34507  성수2가3동주민센터    595237      20201
34508     성수동카페거리    985622      20201
34512  성수1가1동주민센터    137360      20201
34895  성수역 골목형상점가     28534      20194
35004      성수대교남단    993003      20194
35147         성수역   1328804      20194
36152      성수초등학교   1781127      20194
36155   성수119안전센터   1891229      20194
36157  성수2가3동주민센터    587569      20194
36158     성수동카페거리   1102313      20194
36162  성수1가1동주민센터    142209      20194
36545  성수역 골목형상점가     32665      20193
36654      성수대교남단    975107      20193
36797         성수역   1292547      20193
37802      성수초등학교   1127793      20193
37805   성수119안전센터   1866028      20193
37807  성수2가3동주민센터    573407      20193
37808     성수동카페거리   1051117      20193
37812  성수1가1동주민센터    137096      20193
38195  성수역 골목형상점가     31561      20192
38304      성수대교남단    936572      20192
38447         성수역   1235175      20192
39452      성수초등학교   1065392      20192
39455   성수119안전센터   1852359      20192
39457  성수2가3동주민센터    538235      20192
39458     성수동카페거리   1033991      20192
39462  성수1가1동주민센터    125888      20192
39845  성수역 골목형상점가     32084      20191
39954      성수대교남단    946796      20191
40097         성수역   1227980      20191
41102      성수초등학교   1079934      20191
41105   성수119안전센터   1940067      20191
41107  성수2가3동주민센터    547758      20191
41108     성수동카페거리   1020203      20191
41112  성수1가1동주민센터    121850      20191

In [14]:
pd.reset_option('display.max_rows', None)

In [15]:
Commercial_district_data_가로수길 = data[data['상권_코드_명'].str.contains('가로수길', na=False)]

Commercial_district_data_가로수길[['기준_년분기_코드', '상권_코드_명', "총_유동인구_수"]]

       기준_년분기_코드 상권_코드_명  총_유동인구_수
374        20251    가로수길   2167296
2024       20244    가로수길   2274531
3673       20243    가로수길   2293058
5321       20242    가로수길   2345512
6970       20241    가로수길   2318613
8619       20234    가로수길   2395251
10267      20233    가로수길   2414513
11916      20232    가로수길   2378451
13565      20231    가로수길   2406926
15214      20224    가로수길   2453806
16863      20223    가로수길   2492013
18513      20222    가로수길   2447873
20163      20221    가로수길   2123189
21813      20214    가로수길   2282856
23463      20213    가로수길   2197662
25113      20212    가로수길   2441729
26763      20211    가로수길   2382999
28413      20204    가로수길   2280324
30063      20203    가로수길   2352415
31713      20202    가로수길   2444043
33363      20201    가로수길   2358651
35013      20194    가로수길   2466934
36663      20193    가로수길   2343646
38313      20192    가로수길   2358749
39963      20191    가로수길   2425202

In [16]:
# # 분기형 코드(예: 20251 = 2025년 1분기) 처리
# def parse_quarter_str(quarter_str):
#     s = str(quarter_str)
#     if len(s) == 5:
#         year = int(s[:4])
#         quarter = int(s[4])
#         # 분기 첫 달(1,4,7,10월)로 변환
#         month = (quarter - 1) * 3 + 1
#         return pd.Timestamp(year=year, month=month, day=1)
#     elif len(s) == 6:
#         return pd.to_datetime(s, format='%Y%m')
#     else:
#         return pd.NaT


# Commercial_district_data_성수 = data[data['상권_코드_명'].str.contains('성수', na=False)]
# # Commercial_district_data_성수['기준_년분기_코드'] = Commercial_district_data_성수['기준_년분기_코드'].astype(str).str.zfill(6)

# Commercial_district_data_성수['date'] = Commercial_district_data_성수['기준_년분기_코드'].apply(parse_quarter_str)
# Commercial_district_data_성수["date"] = pd.to_datetime(Commercial_district_data_성수['date'], format='YYYYM')
# Commercial_district_data_성수["year"] = Commercial_district_data_성수['date'].dt.year


# Commercial_district_data_성수[['year', "총_유동인구_수"]].groupby(by="year").sum()

In [17]:
# 분기형 코드(예: 20251 = 2025년 1분기) 처리
def parse_quarter_str(quarter_str):
    s = str(quarter_str)
    if len(s) == 5:
        year = int(s[:4])
        quarter = int(s[4])
        # 분기 첫 달(1,4,7,10월)로 변환
        month = (quarter - 1) * 3 + 1
        return pd.Timestamp(year=year, month=month, day=1)
    elif len(s) == 6:
        return pd.to_datetime(s, format='%Y%m')
    else:
        return pd.NaT


Commercial_district_data_성수 = data[data['상권_코드_명'].isin(["성수역 골목형상점가","성수역", "성수동카페거리"])]
# Commercial_district_data_성수['기준_년분기_코드'] = Commercial_district_data_성수['기준_년분기_코드'].astype(str).str.zfill(6)

Commercial_district_data_성수['date'] = Commercial_district_data_성수['기준_년분기_코드'].apply(parse_quarter_str)
Commercial_district_data_성수["date"] = pd.to_datetime(Commercial_district_data_성수['date'], format='YYYYM')
Commercial_district_data_성수["year"] = Commercial_district_data_성수['date'].dt.year


Commercial_district_data_성수[['year', "총_유동인구_수"]].groupby(by="year").sum()

C:\Users\user\AppData\Local\Temp\ipykernel_59684\2543520582.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Commercial_district_data_성수['date'] = Commercial_district_data_성수['기준_년분기_코드'].apply(parse_quarter_str)
C:\Users\user\AppData\Local\Temp\ipykernel_59684\2543520582.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Commercial_district_data_성수["date"] = pd.to_datetime(Commercial_district_data_성수['date'], format='YYYYM')
C:\Users\user\AppData\Local\Temp\ipykernel_59684\2543520582.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Commercial_district_data_성수["year"] = Commercial_district_data_성수['date'].dt.year

      총_유동인구_수
year
2019   9416974
2020   8922167
2021   8834671
2022   8720661
2023   9159186
2024   9549084
2025   2388658

In [18]:
# 분기형 코드(예: 20251 = 2025년 1분기) 처리
def parse_quarter_str(quarter_str):
    s = str(quarter_str)
    if len(s) == 5:
        year = int(s[:4])
        quarter = int(s[4])
        # 분기 첫 달(1,4,7,10월)로 변환
        month = (quarter - 1) * 3 + 1
        return pd.Timestamp(year=year, month=month, day=1)
    elif len(s) == 6:
        return pd.to_datetime(s, format='%Y%m')
    else:
        return pd.NaT


Commercial_district_data_가로수길 = data[data['상권_코드_명'].str.contains('가로수길', na=False)]
# Commercial_district_data_가로수길['기준_년분기_코드'] = Commercial_district_data_가로수길['기준_년분기_코드'].astype(str).str.zfill(6)

Commercial_district_data_가로수길['date'] = Commercial_district_data_가로수길['기준_년분기_코드'].apply(parse_quarter_str)
Commercial_district_data_가로수길["date"] = pd.to_datetime(Commercial_district_data_가로수길['date'], format='YYYYM')
Commercial_district_data_가로수길["year"] = Commercial_district_data_가로수길['date'].dt.year


Commercial_district_data_가로수길[['year', "총_유동인구_수"]].groupby(by="year").sum()

C:\Users\user\AppData\Local\Temp\ipykernel_59684\1330739473.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Commercial_district_data_가로수길['date'] = Commercial_district_data_가로수길['기준_년분기_코드'].apply(parse_quarter_str)
C:\Users\user\AppData\Local\Temp\ipykernel_59684\1330739473.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Commercial_district_data_가로수길["date"] = pd.to_datetime(Commercial_district_data_가로수길['date'], format='YYYYM')
C:\Users\user\AppData\Local\Temp\ipykernel_59684\1330739473.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Commercial_district_data_가로수길["year"] = Commercial_district_data_가로수길['date'].dt.year

      총_유동인구_수
year
2019   9594531
2020   9435433
2021   9305246
2022   9516881
2023   9595141
2024   9231714
2025   2167296

In [19]:
# Commercial_district_data = Commercial_district_data_성수[['year', "총_유동인구_수"]].groupby(by="year").sum()
# Commercial_district_data_가로수길_result = Commercial_district_data_가로수길[['year', "총_유동인구_수"]].groupby(by="year").sum()

Commercial_district_data_성수 = Commercial_district_data_성수.rename(columns={'총_유동인구_수': '성수_총_유동인구_수'})
Commercial_district_data_가로수길 = Commercial_district_data_가로수길.rename(columns={'총_유동인구_수': '가로수길_총_유동인구_수'})

Commercial_district_data = pd.concat([
    Commercial_district_data_성수[['year', "성수_총_유동인구_수"]].groupby(by="year").sum(), 
    Commercial_district_data_가로수길[['year', "가로수길_총_유동인구_수"]].groupby(by="year").sum()
    ],
    axis=1
)
Commercial_district_data.loc[2025] = Commercial_district_data.loc[2025]*4

In [20]:
Commercial_district_data.to_csv("../data/성수가로수길_유동인구_변동추이.csv", index=False)